// frontend/src/views/admin/Providers.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue';
import api from '../../stores/api';
import type { Provider } from '../../types';

const providers = ref<Provider[]>([]);
const loading = ref(true);
const showModal = ref(false);
const editingProvider = ref<Provider | null>(null);
const formData = ref({
  name: '',
  baseUrl: '',
  apiKey: '',
  type: 'openai-compatible',
  status: 'active',
  remark: '',
});

onMounted(async () => {
  await fetchProviders();
});

async function fetchProviders() {
  try {
    const { data } = await api.get('/providers');
    providers.value = data;
  } catch (e) {
    console.error(e);
  } finally {
    loading.value = false;
  }
}

function openCreate() {
  editingProvider.value = null;
  formData.value = { name: '', baseUrl: '', apiKey: '', type: 'openai-compatible', status: 'active', remark: '' };
  showModal.value = true;
}

function openEdit(provider: Provider) {
  editingProvider.value = provider;
  formData.value = { name: provider.name, baseUrl: provider.baseUrl, apiKey: '', type: provider.type, status: provider.status, remark: provider.remark || '' };
  showModal.value = true;
}

async function saveProvider() {
  try {
    if (editingProvider.value) {
      const updateData: any = { ...formData.value };
      if (!updateData.apiKey) delete updateData.apiKey;
      await api.put(`/providers/${editingProvider.value.id}`, updateData);
    } else {
      await api.post('/providers', formData.value);
    }
    showModal.value = false;
    await fetchProviders();
  } catch (e) {
    console.error(e);
  }
}

async function deleteProvider(id: string) {
  if (!confirm('确定删除此供应商？')) return;
  await api.delete(`/providers/${id}`);
  await fetchProviders();
}

async function testProvider(id: string) {
  try {
    const { data } = await api.post(`/providers/${id}/test`);
    alert(`结果: ${data.message}\n响应时间: ${data.responseTime}ms`);
  } catch (e: any) {
    alert(`测试失败: ${e.message}`);
  }
}

function formatStatus(status: string): string {
  return status === 'active' ? '启用' : '禁用';
}
</script>

<template>
  <div>
    <div class="flex items-center justify-between mb-6">
      <h2 class="text-2xl font-bold">供应商管理</h2>
      <button @click="openCreate" class="btn-primary">新增供应商</button>
    </div>

    <div v-if="loading" class="text-gray-400">加载中...</div>

    <div v-else class="grid gap-4">
      <div v-for="p in providers" :key="p.id" class="card p-4">
        <div class="flex items-start justify-between">
          <div>
            <h3 class="font-semibold text-lg">{{ p.name }}</h3>
            <p class="text-sm text-gray-400">{{ p.baseUrl }}</p>
            <p class="text-xs text-gray-500 mt-1">API Key: {{ p.apiKey }}</p>
          </div>
          <div class="flex items-center gap-2">
            <span
              class="px-2 py-1 text-xs rounded"
              :class="p.status === 'active' ? 'bg-green-900/30 text-green-400' : 'bg-red-900/30 text-red-400'"
            >
              {{ formatStatus(p.status) }}
            </span>
          </div>
        </div>
        <div class="mt-4 flex gap-2">
          <button @click="testProvider(p.id)" class="btn-secondary text-sm">测试</button>
          <button @click="openEdit(p)" class="btn-secondary text-sm">编辑</button>
          <button @click="deleteProvider(p.id)" class="text-red-400 hover:text-red-300 text-sm">删除</button>
        </div>
      </div>
    </div>

    <div v-if="showModal" class="fixed inset-0 bg-black/50 flex items-center justify-center p-4">
      <div class="card p-6 w-full max-w-lg">
        <h3 class="text-lg font-semibold mb-4">{{ editingProvider ? '编辑供应商' : '新增供应商' }}</h3>
        <form @submit.prevent="saveProvider" class="space-y-4">
          <div>
            <label class="block text-sm text-gray-400 mb-1">供应商名称</label>
            <input v-model="formData.name" type="text" class="w-full" required />
          </div>
          <div>
            <label class="block text-sm text-gray-400 mb-1">接口地址</label>
            <input v-model="formData.baseUrl" type="url" class="w-full" placeholder="https://api.example.com" required />
          </div>
          <div>
            <label class="block text-sm text-gray-400 mb-1">API 密钥</label>
            <input v-model="formData.apiKey" type="text" class="w-full" :placeholder="editingProvider ? '（留空则保持原值）' : ''" />
          </div>
          <div>
            <label class="block text-sm text-gray-400 mb-1">接口类型</label>
            <select v-model="formData.type" class="w-full">
              <option value="openai-compatible">OpenAI Compatible</option>
            </select>
          </div>
          <div>
            <label class="block text-sm text-gray-400 mb-1">备注</label>
            <input v-model="formData.remark" type="text" class="w-full" />
          </div>
          <div class="flex gap-2">
            <button type="submit" class="btn-primary flex-1">保存</button>
            <button type="button" @click="showModal = false" class="btn-secondary flex-1">取消</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

// src/app/(dashboard)/providers/page.tsx
"use client";

import { useState, useEffect } from "react";
import { cachedJson } from "@/lib/client/api-cache";

interface Provider {
  id: string;
  name: string;
  slug: string;
  provider_type: string;
  base_url: string;
  models_endpoint: string;
  chat_endpoint: string;
  auth_type: string;
  status: string;
  notes: string | null;
}

const PROVIDER_TYPES = ["openai_compatible", "anthropic", "gemini", "openrouter", "custom"];
const DEFAULT_ENDPOINTS: Record<string, { models: string; chat: string; auth: string }> = {
  openai_compatible: { models: "/v1/models", chat: "/v1/chat/completions", auth: "bearer" },
  anthropic: { models: "/v1/models", chat: "/v1/messages", auth: "x-api-key" },
  gemini: { models: "/v1beta/models", chat: "/v1beta/models", auth: "query" },
  openrouter: { models: "/v1/models", chat: "/v1/chat/completions", auth: "bearer" },
  custom: { models: "/v1/models", chat: "/v1/chat/completions", auth: "bearer" },
};

export default function ProvidersPage() {
  const [providers, setProviders] = useState<Provider[]>([]);
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [showForm, setShowForm] = useState(false);
  const [formError, setFormError] = useState<string | null>(null);
  const [editing, setEditing] = useState<Provider | null>(null);
  const [form, setForm] = useState({ name: "", slug: "", provider_type: "openai_compatible", base_url: "", models_endpoint: "/v1/models", chat_endpoint: "/v1/chat/completions", auth_type: "bearer", status: "active", notes: "" });

  const load = async (force = false) => {
    try {
      setLoadError(null);
      const json = await cachedJson<{ data?: Provider[] }>("/api/providers", { force });
      setProviders(json.data || []);
    } catch (err) {
      setLoadError("加载供应商失败：" + String(err));
    } finally {
      setLoading(false);
    }
  };

  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { load(); }, []);

  const handleTypeChange = (type: string) => {
    const defaults = DEFAULT_ENDPOINTS[type] || DEFAULT_ENDPOINTS.openai_compatible;
    setForm((f) => ({ ...f, provider_type: type, models_endpoint: defaults.models, chat_endpoint: defaults.chat, auth_type: defaults.auth }));
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setFormError(null);
    try {
      const url = editing ? `/api/providers/${editing.id}` : "/api/providers";
      const method = editing ? "PUT" : "POST";
      const res = await fetch(url, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) });
      const json = await res.json();
      if (!res.ok || json.error) {
        setFormError(json.error || "保存供应商失败");
        return;
      }
      setShowForm(false);
      setEditing(null);
      resetForm();
      load(true);
    } catch (err) {
      setFormError("保存供应商失败：" + String(err));
    }
  };

  const handleEdit = (p: Provider) => {
    setEditing(p);
    setFormError(null);
    setForm({ name: p.name, slug: p.slug, provider_type: p.provider_type, base_url: p.base_url, models_endpoint: p.models_endpoint, chat_endpoint: p.chat_endpoint, auth_type: p.auth_type, status: p.status, notes: p.notes || "" });
    setShowForm(true);
  };

  const handleDelete = async (id: string) => {
    if (!confirm("确定删除这个供应商？")) return;
    try {
      const res = await fetch(`/api/providers/${id}`, { method: "DELETE" });
      const json = await res.json();
      if (!res.ok || json.error) {
        alert("删除失败：" + (json.error || "未知错误"));
        return;
      }
      load(true);
    } catch (err) {
      alert("删除失败：" + String(err));
    }
  };

  const resetForm = () => setForm({ name: "", slug: "", provider_type: "openai_compatible", base_url: "", models_endpoint: "/v1/models", chat_endpoint: "/v1/chat/completions", auth_type: "bearer", status: "active", notes: "" });

  if (loading) return <div className="text-gray-400">加载中...</div>;
  if (loadError) return (
    <div className="space-y-4">
      <h1 className="text-2xl font-bold text-white">供应商</h1>
      <div className="bg-red-900/30 border border-red-800 rounded p-3 text-sm text-red-300">{loadError}</div>
      <button onClick={() => load(true)} className="px-4 py-1.5 bg-gray-700 hover:bg-gray-600 text-white rounded text-sm">重试</button>
    </div>
  );

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h1 className="text-2xl font-bold text-white">供应商</h1>
        <button onClick={() => { resetForm(); setEditing(null); setFormError(null); setShowForm(true); }} className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded text-sm">添加供应商</button>
      </div>

      {showForm && (
        <form onSubmit={handleSubmit} className="bg-gray-900 border border-gray-800 rounded-lg p-4 space-y-3">
          {formError && <div className="bg-red-900/30 border border-red-800 rounded p-3 text-sm text-red-300">{formError}</div>}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div><label className="block text-xs text-gray-400 mb-1">名称</label><input value={form.name} onChange={(e) => setForm((f) => ({ ...f, name: e.target.value }))} required className="w-full px-3 py-1.5 bg-gray-800 border border-gray-700 rounded text-white text-sm" /></div>
            <div><label className="block text-xs text-gray-400 mb-1">标识</label><input value={form.slug} onChange={(e) => setForm((f) => ({ ...f, slug: e.target.value }))} required className="w-full px-3 py-1.5 bg-gray-800 border border-gray-700 rounded text-white text-sm" /></div>
            <div><label className="block text-xs text-gray-400 mb-1">类型</label><select value={form.provider_type} onChange={(e) => handleTypeChange(e.target.value)} className="w-full px-3 py-1.5 bg-gray-800 border border-gray-700 rounded text-white text-sm">{PROVIDER_TYPES.map((t) => <option key={t} value={t}>{t}</option>)}</select></div>
            <div><label className="block text-xs text-gray-400 mb-1">基础 URL</label><input value={form.base_url} onChange={(e) => setForm((f) => ({ ...f, base_url: e.target.value }))} required placeholder="https://api.openai.com" className="w-full px-3 py-1.5 bg-gray-800 border border-gray-700 rounded text-white text-sm" /></div>
            <div><label className="block text-xs text-gray-400 mb-1">模型列表端点</label><input value={form.models_endpoint} onChange={(e) => setForm((f) => ({ ...f, models_endpoint: e.target.value }))} className="w-full px-3 py-1.5 bg-gray-800 border border-gray-700 rounded text-white text-sm" /></div>
            <div><label className="block text-xs text-gray-400 mb-1">聊天端点</label><input value={form.chat_endpoint} onChange={(e) => setForm((f) => ({ ...f, chat_endpoint: e.target.value }))} className="w-full px-3 py-1.5 bg-gray-800 border border-gray-700 rounded text-white text-sm" /></div>
          </div>
          <div><label className="block text-xs text-gray-400 mb-1">备注</label><textarea value={form.notes} onChange={(e) => setForm((f) => ({ ...f, notes: e.target.value }))} className="w-full px-3 py-1.5 bg-gray-800 border border-gray-700 rounded text-white text-sm" rows={2} /></div>
          <div className="flex gap-2 flex-wrap">
            <button type="submit" className="px-4 py-1.5 bg-blue-600 hover:bg-blue-700 text-white rounded text-sm">{editing ? "更新" : "创建"}</button>
            <button type="button" onClick={() => { setShowForm(false); setEditing(null); }} className="px-4 py-1.5 bg-gray-700 hover:bg-gray-600 text-white rounded text-sm">取消</button>
          </div>
        </form>
      )}

      <div className="space-y-2">
        {providers.map((p) => (
          <div key={p.id} className="bg-gray-900 border border-gray-800 rounded-lg p-4">
            <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
              <div className="flex-1 min-w-0">
                <div className="text-white font-medium">{p.name}</div>
                <div className="text-xs text-gray-500">{p.provider_type} &middot; {p.base_url}</div>
              </div>
              <div className="flex gap-2 shrink-0">
                <button onClick={() => handleEdit(p)} className="px-3 py-1 bg-gray-800 hover:bg-gray-700 text-gray-300 rounded text-xs">编辑</button>
                <button onClick={() => handleDelete(p.id)} className="px-3 py-1 bg-gray-800 hover:bg-red-900/50 text-gray-300 rounded text-xs">删除</button>
              </div>
            </div>
          </div>
        ))}
        {providers.length === 0 && <p className="text-gray-500 text-sm">暂无供应商。</p>}
      </div>
    </div>
  );
}
